project:
  type: book

book:
  title: "Implementation of gMCP in GSD"
  author: "Yevgen Tymofyeyev and Michael Grayling"
  date: last-modified
  chapters:
    - index.qmd
    - template.qmd

bibliography: 
    - gMCP_in_GSD.bib

format:
  html:
    theme: cosmo
    embed-resources: true
    code-fold: true

